services:
  - type: web
    name: ent-lms
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: sh -c "flask db upgrade && gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        fromDatabase:
          name: ent-lms-db
          property: connectionString
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "1"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: APP_PUBLIC_URL
        sync: false

databases:
  - name: ent-lms-db
    plan: free
